//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceP3
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceP3.IMplementInterface")]
    public interface IMplementInterface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/saveImage", ReplyAction="http://tempuri.org/InterfaceImages/saveImageResponse")]
        System.Threading.Tasks.Task saveImageAsync(string Name, string Path, string About, string Place, string People);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/UpdateImage1", ReplyAction="http://tempuri.org/InterfaceImages/UpdateImage1Response")]
        System.Threading.Tasks.Task UpdateImage1Async(string Name, string Path, string About, string Place, string People);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/deleteImage", ReplyAction="http://tempuri.org/InterfaceImages/deleteImageResponse")]
        System.Threading.Tasks.Task deleteImageAsync(string Path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMplementInterfaceChannel : ServiceReferenceP3.IMplementInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MplementInterfaceClient : System.ServiceModel.ClientBase<ServiceReferenceP3.IMplementInterface>, ServiceReferenceP3.IMplementInterface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MplementInterfaceClient() : 
                base(MplementInterfaceClient.GetDefaultBinding(), MplementInterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMplementInterface.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MplementInterfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(MplementInterfaceClient.GetBindingForEndpoint(endpointConfiguration), MplementInterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MplementInterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MplementInterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MplementInterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MplementInterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MplementInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task saveImageAsync(string Name, string Path, string About, string Place, string People)
        {
            return base.Channel.saveImageAsync(Name, Path, About, Place, People);
        }
        
        public System.Threading.Tasks.Task UpdateImage1Async(string Name, string Path, string About, string Place, string People)
        {
            return base.Channel.UpdateImage1Async(Name, Path, About, Place, People);
        }
        
        public System.Threading.Tasks.Task deleteImageAsync(string Path)
        {
            return base.Channel.deleteImageAsync(Path);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMplementInterface))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMplementInterface))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/ALEX");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MplementInterfaceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMplementInterface);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MplementInterfaceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMplementInterface);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMplementInterface,
        }
    }
}
