//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMplementInterface")]
public interface IMplementInterface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/saveImage", ReplyAction="http://tempuri.org/InterfaceImages/saveImageResponse")]
    void saveImage(string Name, string Path, string About, string Place, string People);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/saveImage", ReplyAction="http://tempuri.org/InterfaceImages/saveImageResponse")]
    System.Threading.Tasks.Task saveImageAsync(string Name, string Path, string About, string Place, string People);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/UpdateImage1", ReplyAction="http://tempuri.org/InterfaceImages/UpdateImage1Response")]
    void UpdateImage1(string Name, string Path, string About, string Place, string People);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/UpdateImage1", ReplyAction="http://tempuri.org/InterfaceImages/UpdateImage1Response")]
    System.Threading.Tasks.Task UpdateImage1Async(string Name, string Path, string About, string Place, string People);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/deleteImage", ReplyAction="http://tempuri.org/InterfaceImages/deleteImageResponse")]
    void deleteImage(string Path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceImages/deleteImage", ReplyAction="http://tempuri.org/InterfaceImages/deleteImageResponse")]
    System.Threading.Tasks.Task deleteImageAsync(string Path);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMplementInterfaceChannel : IMplementInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MplementInterfaceClient : System.ServiceModel.ClientBase<IMplementInterface>, IMplementInterface
{
    
    public MplementInterfaceClient()
    {
    }
    
    public MplementInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MplementInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MplementInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MplementInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void saveImage(string Name, string Path, string About, string Place, string People)
    {
        base.Channel.saveImage(Name, Path, About, Place, People);
    }
    
    public System.Threading.Tasks.Task saveImageAsync(string Name, string Path, string About, string Place, string People)
    {
        return base.Channel.saveImageAsync(Name, Path, About, Place, People);
    }
    
    public void UpdateImage1(string Name, string Path, string About, string Place, string People)
    {
        base.Channel.UpdateImage1(Name, Path, About, Place, People);
    }
    
    public System.Threading.Tasks.Task UpdateImage1Async(string Name, string Path, string About, string Place, string People)
    {
        return base.Channel.UpdateImage1Async(Name, Path, About, Place, People);
    }
    
    public void deleteImage(string Path)
    {
        base.Channel.deleteImage(Path);
    }
    
    public System.Threading.Tasks.Task deleteImageAsync(string Path)
    {
        return base.Channel.deleteImageAsync(Path);
    }
}
